spring.application.name=rentease

spring.datasource.url=jdbc:mysql://localhost:3306/rentease
spring.datasource.username=root
spring.datasource.password=jeevitha2007
spring.jpa.hibernate.ddl-auto=update